### ISSUE TITLE
GL Error log spam with keybinds for some mods.

### ISSUE THREAD

**Issue by Felix14-v2** [Siphalor/amecs#36] opened 2021-08-01 13:05 UTC
[[Demo]](https://youtu.be/WAaZR7ad_3Y)
(Sorry for the video quality)

Examples of problematic mods:
[Memory Usage Screen](https://github.com/MORIMORI0317/MemoryUsageScreen/)
[NBT Tooltip](https://github.com/zabi94/NBTTooltip/)

Amecs 1.3.4, Minecraft 1.17.1

[latest.log](https://github.com/Siphalor/amecs/files/6912726/latest.log)

**Comment by Siphalor** [comment] 2021-08-24 17:53
Oh my, this really isn't looking good.

I'm going to see if I can make the reasons out and fix this.

**Comment by Felix14-v2** [comment] 2021-08-26 22:39
Yeah, this is definitely not good.
![image](https://user-images.githubusercontent.com/75726196/131044924-87bec099-3b2b-4648-97ab-4960ae08eea4.png)

Can I help by providing additional necessary information?

**Comment by Klotzi111** [comment] 2021-09-12 23:14
I tried NBT Tooltip together with Amecs and Nmuk (both from my fork) and I can not reproduce this.
And I do not think that I did anything in the render direction. So it should not even be a problem of current Amecs.
The information is very limited but my best guess where the problem comes from is Sodium

You should try to spot the mod which leads to this problem. Thats best done with using the half of your mods and run. If the problem occures you know the problematic mod must be in this half. If not it is in the other half. Continue doing this until you found the problematic mod

**Comment by Felix14-v2** [comment] 2021-09-13 00:49
This issue also occurs without Sodium.

I don't know what can go wrong... Here are all the mods that I tested with:
[mods.zip](https://github.com/Siphalor/amecs/files/7150612/mods.zip)
As you can see, log spam is still happens.

I think this might be useful:
[options.txt](https://github.com/Siphalor/amecs/files/7150628/options.txt)

**Comment by Klotzi111** [comment] 2021-09-13 15:45
I used these excat mods and I still can not reproduce this problem. During what stage of the game does this problem occur? World loading, Main menu, general gameplay?
It might have something to do with your game language.
I will look into that. Please try english (en_us) to test this

**Comment by Klotzi111** [comment] 2021-09-13 18:01
I tried running with the same language then you did: ru_ru. But I still do not get these errors. Maybe it has something to do with your hardware or game overlays that you have active. Please disable all such overlays, remove all resource packs and let the game crash (holding F3 + C for 10 seconds while in game). Then send me the latest.log

**Comment by Klotzi111** [comment] 2021-09-13 22:12
As I could see in the latest.log you are still having more mods than you should if you want to test whether Amecs causes problems with Memory Usage Screen or NBT Tooltip.
Please remove the following mods and try again:
```
AzerusTeam
Happy Birthday
TeslaCraft!
”лучшенное меню
```

**Comment by Felix14-v2** [comment] 2021-09-14 10:06
Minecraft Launcher in its repertoire: [[Demo]](https://youtu.be/OQacaEAWPHo) 
[2021-09-14-1.log](https://github.com/Siphalor/amecs/files/7160796/2021-09-14-1.log)
[2021-09-14-2.log](https://github.com/Siphalor/amecs/files/7160798/2021-09-14-2.log)
[crash-2021-09-14_12.10.57-client.txt](https://github.com/Siphalor/amecs/files/7160842/crash-2021-09-14_12.10.57-client.txt)
[crash-2021-09-14_12.13.04-client.txt](https://github.com/Siphalor/amecs/files/7160843/crash-2021-09-14_12.13.04-client.txt)


Another way: [[Demo]](https://youtu.be/1Hu5BxKScTw)
[2021-09-14-1.log](https://github.com/Siphalor/amecs/files/7160957/2021-09-14-1.log)
[tlauncher.log](https://github.com/Siphalor/amecs/files/7160826/tlauncher.log)
[tl-logger7284427634299775596.txt](https://github.com/Siphalor/amecs/files/7160832/tl-logger7284427634299775596.txt)
[crash-2021-09-14_12.32.25-client.txt](https://github.com/Siphalor/amecs/files/7160838/crash-2021-09-14_12.32.25-client.txt)

Sorry for stopping recording some moments, vanilla minecraft is too laggy.

**Comment by Felix14-v2** [comment] 2021-09-14 13:26
> ```
> AzerusTeam
> Happy Birthday
> TeslaCraft!
> ”лучшенное меню
> ```

These are resourcepacks, not mods, by the way. But even with a clean installation, the problem still persists. I can't even imagine what could be wrong.
I even tested the same mods in minecraft 1.16.5 and got the same result.

**Comment by Klotzi111** [comment] 2021-09-14 13:52
Thanks for that detailed information. Now I have a good chance at finding the cause. I will let you know what I find (or not find)

**Comment by Klotzi111** [comment] 2021-09-14 13:54
With the information given I was able to reproduce the problem. That was the most important part

**Comment by Siphalor** [comment] 2021-09-14 15:14
Heyho, a lot is going on here :)

I think the cause of the GL errors is that both of these mods (and possibly also a bunch of other ones) call to pretty thin wrappers around GL functions like here:

https://github.com/MORIMORI0317/MemoryUsageScreen/blob/18e5084a0d7956128a906d030eddd9806097f14e/src/main/java/net/morimori/mus/mixin/MinecraftMixin.java#L25

or here:

https://github.com/zabi94/NBTTooltip/blob/7c3e38adbf8d5b2e018202de6a6c50f37ddca3e2/src/main/java/zabi/minecraft/nbttooltip/NBTTooltip.java#L114

Since at least some of the codes that Amecs uses are non-standard (like the scrolling) this can blow up.
I'm not sure why the `-1` is broken though.

The solution might be to mixin to `InputConstants` and `InputUtil`.
I don't really like that tho :/

**Comment by Klotzi111** [comment] 2021-09-14 15:25
I also found the cause of the problem in MemoryUsageScreen and fixed it already (I made a pull request)
I am going to do that for NBTTooltip as well.

As @Siphalor mentioned we COULD mixin to InputUtil (yarn)/InputConstants (mojang) but we SHOULD NOT. Since this method is designed for keyboard keys ONLY. But these mods call it with any key that is bound to the binding (this would also have caused the same problem without Amecs since vanilla supports mouse buttons)

**Comment by Klotzi111** [comment] 2021-09-25 11:27
The problem is fixed in MemoryUsageScreen with my prs merged.
I also made a pr for NBTTooltip but he does not want to merge it. There is nothing I can do more.
If you want the fixed NBTTooltip version you have to compile my forked repo youself:
https://github.com/Klotzi111/NBTTooltip

**Closed as completed** 2021-09-25 13:04 UTC
Labels: bug
